version: '3.5'

services:
  nats_1:
    image: nats
    ports:
      - 127.0.0.1:4222:4222
  nats_2:
    image: nats
    ports:
      - 127.0.0.1:4223:4222
  nats_tls:
    image: nats
    ports:
      - 127.0.0.1:4224:4222
    volumes:
      - './certs:/certs:ro'
    command: --tls --tlscert=/certs/server.crt --tlskey=/certs/server.key
