name: CI

on:
  push:
    branches: [ master ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    permissions:
      contents: read
      packages: read

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install goveralls
        env:
          GO111MODULE: off
        run: go get github.com/mattn/goveralls

      - name: Lint with golangci-lint
        uses: golangci/golangci-lint-action@v2

      - name: Run Unit tests
        run: |
          go test -covermode atomic -coverprofile=covprofile .

      - name: Send coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: goveralls -coverprofile=covprofile -service=github

  analyze:
    name: Analyze
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        language: [ 'go' ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: ${{ matrix.language }}

      - name: Autobuild
        uses: github/codeql-action/autobuild@v1

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1

  release:
    name: Release
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    needs:
     - test
     - analyze

    permissions:
      contents: write
      packages: write

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: GHCR Login
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.actor }}
        run: |
          echo ${GITHUB_TOKEN} | docker login ghcr.io -u ${USERNAME} --password-stdin

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy tagged to ghcr.io
        env:
          GITHUB_PACKAGE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REF:
        run: |
          echo ${GITHUB_PACKAGE_TOKEN} | docker login ghcr.io -u ${GITHUB_ACTOR} --password-stdin
          docker buildx build --push \
              --platform linux/amd64,linux/arm64 \
              -t ghcr.io/${GITHUB_REPOSITORY}:${{ steps.tag.outputs.tag }} \
              -t ghcr.io/${GITHUB_REPOSITORY}:latest \
              .
