name: Build

on:
  push:
    branches: [ master ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Lint with golangci-lint
        uses: golangci/golangci-lint-action@v2

      - name: Run GoReleaser
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: deploy tagged to ghcr.io
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        env:
          GITHUB_PACKAGE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REF: ${github.ref}
        run: |
          echo ${GITHUB_PACKAGE_TOKEN} | docker login ghcr.io -u ${GITHUB_ACTOR} --password-stdin
          docker buildx build --push \
              --platform linux/amd64,linux/arm64 \
              -t ghcr.io/${GITHUB_REPOSITORY}/nats-resender:${GITHUB_REF} \
              -t ghcr.io/${GITHUB_REPOSITORY}/nats-resender:latest
